compile:
  libraries:
    - uno
  platforms:
    uno:
      gcc:
        flags: -DDEBUG -DINFO -DTEST -DDUMMY -fprofile-arcs -ftest-coverage -fPIC -O0

unittest:
  libraries: 
    - uno
  platforms:
    - uno