platforms:
  uno-compatible:
    board: arduino:avr:uno
    package: arduino:avr
    gcc:
      features:
        - profile-arcs
        - test-coverage
      defines:
        - DEBUG
        - TEST
        - __AVR_ATmega328P__
      flags:
        - -lgcov
  mega-compatible:
    board: arduino:avr:mega:cpu=atmega2560
    package: arduino:avr
    gcc:
      features:
        - profile-arcs
        - test-coverage
      defines:
        - DEBUG
        - TEST
        - __AVR_ATmega2560__
      flags:
        - -lgcov

compile:
  libraries: ~
  platforms:
    - mega-compatible
  #exclude_dirs:
  #  - gcovr
  
unittest:
  libraries: ~
  platforms:
    - uno-compatible
  #exclude_dirs:
  #  - gcovr
  