platforms:
  uno-ext:
    board: arduino:avr:uno
    package: arduino:avr
    gcc:
      features:
        - fprofile-arcs
        - ftest-coverage
      defines:
        - DDEBUG
        - DTEST
        - __AVR_ATmega328P__
      warnings:
      flags:

  mega2560-ext:
    board: arduino:avr:mega:cpu=atmega2560
    package: arduino:avr
    gcc:
      features:
        - fprofile-arcs
        - ftest-coverage
      defines:
        - DDEBUG
        - DTEST
        - __AVR_ATmega2560__
      warnings:
      flags:
      
compile:
  libraries: ~
  platforms:
    - mega2560-ext
  #exclude_dirs:
  #  - gcovr
  
unittest:
  libraries: ~
  platforms:
    - uno-ext
  #exclude_dirs:
  #  - gcovr
  