platforms:
  uno-compatible:
    board: arduino:avr:ATmega328P
    package: arduino:avr
    gcc:
      features:
      defines:
        - DEBUG
        - TEST
        - __AVR_ATmega328P__
      warnings:
      flags:
        - -fprofile-arcs -ftest-coverage -lgcov O0

compile:
  libraries: ~
  exclude_dirs:
    - ./gcovr
  platforms:
    - uno-compatible

unittest:
  libraries: ~
  exclude_dirs:
    - ./gcovr
  platforms:
    - uno-compatible