platforms:
  uno-compatible:
    #board: arduino:avr:uno
    board: arduino:avr:mega:cpu=atmega2560
    package: arduino:avr
    gcc:
      features:
      defines:
        - DEBUG
        - TEST
        - __AVR_ATmega2560__
     #   - __AVR_ATmega328P__
      warnings:
      flags:
        - -fprofile-arcs -ftest-coverage -lgcov

compile:
  libraries: ~
  exclude_dirs:
    - ./gcovr
  platforms:
    - uno-compatible

unittest:
  libraries: ~
  exclude_dirs:
    - ./gcovr
  platforms:
    - uno-compatible