platforms:
  uno:
    board: arduino:avr:uno
    package: arduino:avr
    gcc:
      features:
        - profile-arcs
        - test-coverage
      defines:
        - DEBUG
        - TEST
        - __AVR_ATmega328P__
      warnings:
      flags:
        - -lgcov

  mega2560:
    board: arduino:avr:mega:cpu=atmega2560
    package: arduino:avr
    gcc:
      features:
        - profile-arcs
        - test-coverage
      defines:
        - DEBUG
        - TEST
        - __AVR_ATmega2560__
      warnings:
      flags:
        - -v
        - -lgcov

compile:
  libraries: ~
  platforms:
    - mega2560
  #exclude_dirs:
  #  - gcovr
  
unittest:
  libraries: ~
  platforms:
    - uno
  #exclude_dirs:
  #  - gcovr
  