platforms:
  uno-compatible:
    board: arduino:avr:uno
    package: arduino:avr
    gcc:
      features:
      defines:
        - DEBUG
        - INFO
        - TEST
        - DUMMY
        - __AVR_ATmega328P__
      warnings:
      flags:
        - -fprofile-arcs
        - -ftest-coverage

compile:
  libraries: ~
  platforms:
    - uno-compatible

unittest:
  libraries: ~
  platforms:
    - uno-compatible