platforms:
  uno-ext:
    board: arduino:avr:uno
    package: arduino:avr
    gcc:
      features:
        - profile-arcs
        - test-coverage
      defines:
        - DEBUG
        - TEST
        - __AVR_ATmega328P__
      warnings:
      flags:
        - -lgcov

  mega2560-ext:
    board: arduino:avr:mega:cpu=atmega2560
    package: arduino:avr
    gcc:
      features:
        - profile-arcs
        - test-coverage
      defines:
        - DEBUG
        - TEST
        - __AVR_ATmega2560__
      warnings:
      flags:
        - -v
        - -lgcov

compile:
  compilers:
    - gcc
  libraries: ~
  platforms:
    - mega2560-ext
  #exclude_dirs:
  #  - gcovr
  
unittest:
  compilers:
    - gcc
  libraries: ~
  platforms:
    - uno-ext
  #exclude_dirs:
  #  - gcovr
  