paltforms:
  uno-compatible:
    board: arduino:avr:uno
    package: arduino:avr
    gcc:
      flags: -fprofile-arcs -ftest-coverage -fPIC -O0

compile:
  libraries: ~
  platforms:
    - uno-compatible
    #uno:
      #board: arduino:avr:uno
      #package: arduino:avr
      #gcc:
        #flags: -fprofile-arcs -ftest-coverage -fPIC -O0

unittest:
  libraries: ~
  platforms:
    - uno-compatible