compile:
  libraries: ~
  platforms:
    - uno
    #uno:
      #board: avr:uno:r3
      #package: avr:uno
      #gcc:
        #flags: -fprofile-arcs -ftest-coverage -fPIC -O0

unittest:
  libraries: ~
  platforms:
    - uno