platforms:
  uno-compatible:
    #board: arduino:avr:uno
    board: arduino:avr:mega:cpu=atmega2560
    package: arduino:avr
    gcc:
      defines:
        - DEBUG
        - TEST
        - __AVR_ATmega2560__
     #   - __AVR_ATmega328P__
      flags:
        - -fprofile-arcs 
        - -ftest-coverage 
        - -lgcov

compile:
  libraries: ~
  platforms:
    - uno-compatible
  #exclude_dirs:
  #  - ./gcovr
  
unittest:
  libraries: ~
  platforms:
    - uno-compatible
  #exclude_dirs:
  #  - ./gcovr
  