codecov:
  token: ${{ Secrets.CODECOV_TOKEN }}
  ci:
    - "travis.org"
  require_ci_to_pass: yes
  
# Repository Yaml
coverage:
  round: up
  range: 0..10

# Used in Codecov after updating
coverage:
  round: up
  range: 0..10
  precision: 5