# This is a basic workflow to help you get started with Actions

name: "Arduino Build Test"

# Controls when the action will run. Triggers the workflow on push or pull request events
on: [ push, pull_request ]

jobs:
  build:
    name: Test compile for ${{ matrix.arduino-boards-fqbn }} with ${{ matrix.log-options }} ${{ matrix.other-options }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arduino-boards-fqbn: 
          - arduino:avr:uno
          - arduino:avr:leonardo
          - arduino:avr:nano
        log-options: [-DDEBUG, -DINFO]
        other-options: [-DTEST, -DDUMMY]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout LiquidCrystal_I2C library
      uses: actions/checkout@v2
      with:
        repository: johnrickman/LiquidCrystal_I2C
        ref: master
        path: CustomLiquidCrystal_I2C

    - name: Compile
      uses: ArminJo/arduino-test-compile@v2
      with:
        arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }}
        build-properties: '{ "All": "${{ matrix.log-options }} ${{  matrix.other-options }}" }'

    - name: Generate codecov report with travis
      run: |
        chmod +x ./build.sh ./travis_qmake_gcc_cpp11_gcov ./get_code_cov.sh
        ./build.sh
        ./travis_qmake_gcc_cpp11_gcov
        ./get_code_cov.sh

    # request codecov to detect CI environment to pass through to docker
    - name: Upload report to codecov
      run: |
        bash <(curl -s https://codecov.io/bash) -t ${{ Secrets.CODECOV_TOKEN }}