name: "Make manual build"
on:
  push: {branches: develop}
  pull_request: {branches: develop}

jobs:
  build:
    name: Test build with make
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        WORK_DIR: ['/home/runner/work/LCD_VU/LCD_VU']

    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.8'      
      ARDUINO_DIR: '${{matrix.WORK_DIR}}/bin'
      ARDMK_DIR: '${{matrix.WORK_DIR}}/Arduino_MK'
      AVR_TOOLS_DIR: '${{matrix.WORK_DIR}}/AVR_Tool' #Directory where avr tools are installed
      USER_LIB_PATH: '${{matrix.WORK_DIR}}/Lib'
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout LiquidCrystal_I2C library
      uses: actions/checkout@master
      with:
        repository: johnrickman/LiquidCrystal_I2C
        ref: master
        path: ${{ env.USER_LIB_PATH }}/LiquidCrystal_I2C

    - name: Checkout Arduino Makefile
      uses: actions/checkout@master
      with:
        repository: sudar/Arduino-Makefile
        ref: master
        path: ${{ env.ARDMK_DIR }}

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
      
    - name: Upgrade Python
      run: python -m pip install --upgrade pip

    - name: Setup Python Serial
      run: pip install pyserial

    - name: Setup Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        export PATH=$PATH:${{ env.ARDUINO_DIR }}
        export ARDUINO_DIR=${{ env.ARDUINO_DIR }}
        export ARDMK_DIR=${{ env.ARDMK_DIR }}
        export AVR_TOOLS_DIR=${{ env.AVR_TOOLS_DIR }}
        export USER_LIB_PATH=${{ env.USER_LIB_PATH }}
        export WORK_DIR=${{ matrix.WORK_DIR }}

    - name: Install Dependencies
      run: |
        sudo apt-get install libdevice-serialport-perl
        sudo apt-get install libyaml-perl
        
    - name: Init makefile
      run: |
        ${{ env.ARDMK_DIR }}/bin/ardmk-init -v -d ${{ matrix.WORK_DIR }}/script -b uno
        ls -al ${{ matrix.WORK_DIR }}/script

    - name: Make Arduino
      run: make ${{ matrix.WORK_DIR }}/script/Makefile
    
